### ISSUE TITLE
Encode Fails

### ISSUE THREAD

**Issue by MattGrdinic** [avid0/Alom#11]
Super interesting project, unfortunately fails for me using the test code:

```
<?php
function t() {} $r = 1; echo 1;
?>
```

The calling function is:

```
<?php
require_once "../alomencoder.obfs.php";

$settings = [
  'rounds' => [
    'main' => [
      'depth' => 1
    ]
  ]
];
$obfs = AlomEncoder::obfuscator('simple-source.php', $settings);
file_put_contents('simple-source.obfs.php', $obfs); // save obfuscated script
?>
```

The actual error (when setting):

`'hide_errors' => false,`

is:

`Parse error: syntax error, unexpected '}' `

When I set this however:

`'hide_eval' => false`

The error goes away and the encoded page runs as expected. 

One other quick item I've noted is if the script doesn't have an ending PHP block we'll receive:

`Alom Error:   Script error: syntax error, unexpected '<' on line 327 `

**Comment by avid0** [comment]
Fixed in version 2.5
thanks
