### ISSUE TITLE
Not able to encode with version 2.5, Getting Error  

### ISSUE THREAD

**Issue by elite-graphix** [avid0/Alom#12]
Thanks for your encoder, i am trying to use your encoder to encode a file and i am getting error

`Alom Error:   Script error: syntax error, unexpected 'use' (T_USE) on line 11`

on line 11 its

`use PHPMailer\ PHPMailer\ PHPMailer;`

below is code until line 15

```
ob_start();
if(substr_count($_SERVER['HTTP_ACCEPT_ENCODING'], 'gzip'))ob_start("ob_gzhandler");
else ob_start();
session_start();
if(file_exists("admin/includes/config.php")) {
 include("admin/includes/config.php");
} else {
 header("Location: setup");
}
use PHPMailer\ PHPMailer\ PHPMailer;
use PHPMailer\ PHPMailer\ SMTP;
use PHPMailer\ PHPMailer\ Exception;
$admin_logged_in = admin_logged_in();
ini_set("auto_detect_line_endings", true);
```

Kindly check and provide me solution if you please, although i am able to encode this file with version 2.2 without any errors, its 2.5 which is giving error and also to your knowledge version 2.3 and 2.4 are also giving the same error.
Thanks

**Comment by avid0** [comment]
Fixed in sub-version 2.5.1 .
This bug is created to check the syntax when using "use" or "const".
thanks for help

**Comment by elite-graphix** [comment]
Thanks for a quick fix, i am getting another error now and i think this is because of anonymous function the error is 

`Alom Error:   Script error: syntax error, unexpected '}', expecting '{' on line 2017`

and the function is 
```
$keyword = array_filter($keyword, function($v)use($min) {
   return !!($v > $min); // LINE NO 2017
  });

**Comment by avid0** [comment]
Yes that is for anonymous function with use statement, thanks again.
Fixed in 2.5.2 .

**Comment by elite-graphix** [comment]
Thanks for the fix, file is now encoded without error but, i have got another error when i try to run the file

`Fatal error: Uncaught Error: Call to a member function prepare() on null in /Volumes/Workshop/Websites/ecmsprime/includes/functions.php(4) : eval()'d code(1) : eval()'d code:1 Stack trace: #0 /Volumes/Workshop/Websites/ecmsprime/includes/functions.php(4) : eval()'d code(1) : eval()'d code(1): get_navigation_array(0, '', true) #1 /Volumes/Workshop/Websites/ecmsprime/includes/functions.php(4) : eval()'d code(1) : eval()'d code(1): display_main_navigation() #2 /Volumes/Workshop/Websites/ecmsprime/includes/functions.php(4) : eval()'d code(1) : eval()'d code(49): website_placeholders_array() #3 /Volumes/Workshop/Websites/ecmsprime/includes/functions.php(4) : eval()'d code(1) : eval()'d code(36): error404() #4 /Volumes/Workshop/Websites/ecmsprime/includes/functions.php(4) : eval()'d code(1) : eval()'d code(1): get_page_content() #5 /Volumes/Workshop/Websites/ecmsprime/index.php(84): get_website() #6 {main} thrown in /Volumes/Workshop/Websites/ecmsprime/includes/functions.php(4) : eval()'d code(1) : eval()'d code on line 1`

prepare is 
`$stmt = $dbh->prepare()`

if you want i could provide you the functions file for further investigation.
Thanks

**Comment by avid0** [comment]
There is no bug.
If you encode two scripts with using the rounds.ummeaning option at two different times, the two scripts will not be able to recognize each other's variables. You have three solutions:
1. Encode two scripts with just one library call.
2. Or remove the rounds.ummeaning option from the settings:
    $settings['rounds']['unmeaning']['variables'] = false;
3. Or set a fixed value for the rounds.ummeaning option for both scripts.
    $settings['rounds']['unmeaning']['salt'] = "an fixed salt string";

**Comment by elite-graphix** [comment]
Okay, i was encoding only one file other is not encoded, i will try your provided solution tomorrow and let you know, what happens. thanks for your help.

**Comment by elite-graphix** [comment]
Hello buddy, getting the same error even after setting variables "false" using below settings

```$settings = [
  'rounds' => [
    'main' => [
      'depth' => 1
    ],
   'unmeaning' => [
    'variables' => false
   ]
  ],
  'license' => [
   'type' => 'remove',
    'title' => 'example',
    'author' => 'Avid'
  ]
];

**Comment by avid0** [comment]
Fixed in version 2.6.0 (i think -_-)

**Comment by elite-graphix** [comment]
Hello, same error with 2.6, although encoded with 2.2 is working fine.

**Comment by avid0** [comment]
Hi, I checked again but I did not find any problems.
If possible, can I have your file to find the problem?
Also, if you want, you can send it to me personally in the telegram. My username is @Av_id

**Comment by elite-graphix** [comment]
Hello, yes i will do it, wait pining you on telegram

**Comment by avid0** [comment]
I solved all the possible problems. If there is a clear problem, tell me. Thank you.
