### ISSUE TITLE
Debugging & Breakpoint vulnerability

### ISSUE THREAD

**Issue by 0x11DFE** [avid0/Alom#2]
Been looking for a easier way of getting the unprotected code and yet there is one.
Since there is no anti debug tricks i am able to get any native function that is executed.
The solution could be adding anti debug checks or making the attack vector a lot smaller.

[gzinflate BP Vulnerability](https://github.com/0x11DFE/Alom#20-gzinflate-bp-vulnerability)

**Comment by Serqati** [comment]
:joy:

**Comment by Serqati** [comment]
How to write anti-debug?
maybe a open source anti debug or a base for that ?

**Comment by 0x11DFE** [comment]
I'm using [Xdebug](https://xdebug.org/docs/install).

**Comment by kingapk** [comment]
> I'm using [Xdebug](https://xdebug.org/docs/install).

Hi, if you have time, learn how to decrypt version 1.6 of this encryption. Grateful.

**Comment by kingapk** [comment]
> How to write anti-debug?
> maybe a open source anti debug or a base for that ?

Hi, if you have time, learn how to decrypt version 1.6 of this encryption. Grateful.

**Comment by 0x11DFE** [comment]
> > I'm using [Xdebug](https://xdebug.org/docs/install).
> 
> Hi, if you have time, learn how to decrypt version 1.6 of this encryption. Grateful.
> 
> If you can help in Telegram and if not in GateHub My Telegram ID: @xgamerv

The procedee should be the same.

**Comment by kingapk** [comment]
> > > I'm using [Xdebug](https://xdebug.org/docs/install).
> > 
> > 
> > Hi, if you have time, learn how to decrypt version 1.6 of this encryption. Grateful.
> > If you can help in Telegram and if not in GateHub My Telegram ID: @xgamerv
> 
> The procedee should be the same.

If you can make an instructional video and send a telegram, thank you. It is for posting on YouTube, the name of the video creator is also included.

**Comment by 0x11DFE** [comment]
> > > > I'm using [Xdebug](https://xdebug.org/docs/install).
> > > 
> > > 
> > > Hi, if you have time, learn how to decrypt version 1.6 of this encryption. Grateful.
> > > If you can help in Telegram and if not in GateHub My Telegram ID: @xgamerv
> > 
> > 
> > The procedee should be the same.
> 
> If you can make an instructional video and send a telegram, thank you. It is for posting on YouTube, the name of the video creator is also included.

I'm not going to make any youtube video's. Follow the guide i wrote https://github.com/0x11DFE/Alom

**Comment by kingapk** [comment]
> > > > > I'm using [Xdebug](https://xdebug.org/docs/install).
> > > > 
> > > > 
> > > > Hi, if you have time, learn how to decrypt version 1.6 of this encryption. Grateful.
> > > > If you can help in Telegram and if not in GateHub My Telegram ID: @xgamerv
> > > 
> > > 
> > > The procedee should be the same.
> > 
> > 
> > If you can make an instructional video and send a telegram, thank you. It is for posting on YouTube, the name of the video creator is also included.
> 
> I'm not going to make any youtube video's. Follow the guide i wrote https://github.com/0x11DFE/Alom

Provide at least one tutorial on this call

**Comment by avid0** [comment]
obfuscatoring of the original file is not secure enough.
Please read the complete documentation to increase the security of your obfuscatored scripts.
And of course, in the new version, you can use [partitioning round](https://github.com/avid0/Alom/blob/main/README.md#rounds) to protect scripts.

**Comment by avid0** [comment]
I will provide better methods after further research.

**Comment by avid0** [comment]
Fixed with version 2.2 . You can use round antidebugger(by default) for fix that.

**Comment by 0x11DFE** [comment]
> Fixed with version 2.2 . You can use round antidebugger(by default) for fix that.

After further reversing of the protected file i found another vulnterability or missconfiguration and i was able to get the source of the latest version (2.2).

After writing the new procedee i will update the issue.

**Comment by 0x11DFE** [comment]
Here is my [procedee to bypass your anti debug](https://github.com/0x11DFE/Alom#22-bypass-anti-debug).
