### ISSUE TITLE
How to decode  ?

### ISSUE THREAD

**Issue by Trustdee** [avid0/Alom#3]
Mistakenly encoded my source and can not decode ,  will like some help.

**Comment by 0x11DFE** [comment]
Have a look at the fork i made explaining my walkthrough unpacking the protector by using some of its vulnerabilities.
https://github.com/0x11DFE/Alom

**Comment by avid0** [comment]
obfuscatoring of the original file is not secure enough.
Please read the complete documentation to increase the security of your obfuscatored scripts.
And of course, in the new version, you can use [partitioning round](https://github.com/avid0/Alom/blob/main/README.md#rounds) to protect scripts.

I will provide better methods after further research.

**Comment by Dichvucoder** [comment]
Inb telegram @dichvucoder
I can decode

**Comment by ghost** [comment]
Decode all version alom and php encoded file except ioncube and sourceguardian:
https://t.me/phpdecoder_bot
