### ISSUE TITLE
Breaking when using $this

### ISSUE THREAD

**Issue by Shadow505** [avid0/Alom#7]
Hello,

the compiled code is not working when `$this` is being used. It will fail with:

_Cannot use $this as global variable_

Example code:

```
<?php

class Test
{
	public $abc;

	public function xyz($val)
	{
		$this->abc = $val;
	}
}

$Test = new Test();
$Test->xyz('Something...');
var_dump($Test->abc);
```

**Comment by avid0** [comment]
Fixed with version 2.2 . Thanks to help improve the Alom.
