### ISSUE TITLE
Anti Debug vulnerability

### ISSUE THREAD

**Issue by 0x11DFE** [avid0/Alom#9]
Since there is a new anti debug component i think it's okay to open an issue since i done a bypass for it.
[Procedee to bypass the anti debug](https://github.com/0x11DFE/Alom#22-bypass-anti-debug).

**Comment by avid0** [comment]
fixed in version 2.3
+ antidebugger updated to resist XDebug, ZenDebugger, Uopz, Hooking, UnknownDebuggers.

**Comment by 0x11DFE** [comment]
Not fixed was able to debug the file and get the obfuscated code.
Re-open the issue and i will give solution.

**Comment by Serqati** [comment]
@0x11DFE 
What is the solution ?

**Comment by ngontayg123** [comment]
any update on this?

**Comment by 0x11DFE** [comment]
For everyone wondering why it takes so long for an update the answer is simple.
I am pretty bussy working on a project and since i found two ways into solving it i was wondering which one to post.
There is a simple one and a more complex but i might post the simple solution first.

**Comment by 0x11DFE** [comment]
Here is an easy solution.
https://github.com/0x11DFE/Alom#23-exception-leaking

**Comment by Serqati** [comment]
Fixed in #10 PR 
Thanks for the information you've shared.

**Comment by avid0** [comment]
fixed in version 2.4
